### ISSUE TITLE
[Front-end] Show location in pdf

### ISSUE THREAD

**Issue by leonbotros** [privacybydesign/irma-welkom#11]

**Comment by leonbotros** [comment]
Which PDF are we talking about, the contact pdf or the qr pdf? (Or both?)

**Comment by bvgastel** [comment]
Depending on the other email issue, the contact PDF may not be generated anymore.

The location in the QR PDF does not add extra safety (because it is easily adjustable/modified). Although it is useful if you print out a bunch of codes.

For safety the location check should be performed inside the IRMA app, and the location should be inside the QR code.
